apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: test-pod
spec:
  containers:
  - name: test-pod
    image: 192.168.1.3:3000/binayakd/spark:3.5.4-java17-python3
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
 
