apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - minio.yaml
  - spark-history-server.yaml
  - spark-jupyter.yaml

# change the images names as per build
images:
  - name: spark-aws
    newName: 192.168.1.3:3000/binayakd/spark-aws
    newTag: 3.5.4
  - name: spark-jupyter
    newName: 192.168.1.3:3000/binayakd/spark-aws-jupyter
    newTag: 3.5.4