apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: spark
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: spark
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        env:
          - name: "MINIO_ROOT_USER"
            value: "sparkminio"
          - name: "MINIO_ROOT_PASSWORD"
            value: "sparkminio"
        command:
          - /bin/bash
          - -c
        args: 
          - minio server /data --console-address :9090
        resources: {}
        volumeMounts:
          - mountPath: /data
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.5
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: webui
      port: 9090
      targetPort: 9090
      protocol: TCP
  type: LoadBalancer
