apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-conf
  namespace: spark
data:
  spark-defaults.conf: |
    # minio connection config
    spark.hadoop.fs.s3a.access.key=sparkminio
    spark.hadoop.fs.s3a.secret.key=sparkminio
    spark.hadoop.fs.s3a.endpoint=http://192.168.1.5:9000
    spark.hadoop.fs.s3a.path.style.access=true
    spark.hadoop.fs.s3a.connection.ssl.enabled=false

    # spark history server configs
    spark.history.fs.logDirectory=s3a://spark-on-kube/event-logs/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  namespace: spark
spec:
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      labels:
        app: spark-history-server
    spec:
      containers:
      - name: spark-history-server
        image: spark-aws:v1
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "/opt/spark/sbin/start-history-server.sh"]
        env:
          - name: SPARK_NO_DAEMONIZE
            value: "true"
        volumeMounts:
          - name: spark-conf
            mountPath: /opt/spark/conf/spark-defaults.conf
            subPath: spark-defaults.conf
        resources: {}
      volumes:
        - name: spark-conf
          configMap:
            name: spark-conf
            items:
            - key: spark-defaults.conf
              path: spark-defaults.conf
---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.6
  labels:
    app: spark-history-server
spec:
  selector:
    app: spark-history-server
  ports:
    - name: http
      port: 18080
      targetPort: 18080
      protocol: TCP
  type: LoadBalancer
