apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-pvc
  namespace: spark
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  namespace: spark
  labels:
    app: jupyter
spec:
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      serviceAccountName: spark
      securityContext:
        fsGroup: 2000
      containers:
      - name: jupyter
        image: spark-jupyter:v1
        imagePullPolicy: Always
        env:
          - name: TOKEN
            value: sparkjupyter
          - name: PASSWORD
            value: sparkjupyter
        resources: {}
        volumeMounts:
          - mountPath: /home/spark/workspace
            name: workspace
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: jupyter-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.7
  labels:
    app: jupyter
spec:
  selector:
    app: jupyter
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      protocol: TCP
  type: LoadBalancer
