apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  namespace: spark
  labels:
    app: jupyter
spec:
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      serviceAccountName: spark
      securityContext:
        fsGroup: 2000
      containers:
      - name: jupyter
        image: 192.168.1.3:3000/binayakd/spark-aws-jupyter:3.5.4
        imagePullPolicy: Always
        env:
          - name: TOKEN
            value: sparkjupyter
          - name: PASSWORD
            value: sparkjupyter
        resources: {}
        volumeMounts:
          - mountPath: /home/spark/workspace
            name: workspace
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: jupyter-pvc

