apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  namespace: spark
spec:
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      labels:
        app: spark-history-server
    spec:
      containers:
      - name: spark-history-server
        image: 192.168.1.3:3000/binayakd/spark-aws:3.5.4
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "/opt/spark/sbin/start-history-server.sh"]
        env:
          - name: SPARK_NO_DAEMONIZE
            value: "true"
        volumeMounts:
          - name: spark-conf
            mountPath: /opt/spark/conf/spark-defaults.conf
            subPath: spark-defaults.conf
        resources: {}
      volumes:
        - name: spark-conf
          configMap:
            name: spark-conf
            items:
            - key: spark-defaults.conf
              path: spark-defaults.conf


      
