apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.6
  labels:
    app: spark-history-server
spec:
  selector:
    app: spark-history-server
  ports:
    - name: http
      port: 18080
      targetPort: 18080
      protocol: TCP
  type: LoadBalancer
