apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-conf
  namespace: spark
data:
  spark-defaults.conf: |
    # minio connection config
    spark.hadoop.fs.s3a.access.key=sparkminio
    spark.hadoop.fs.s3a.secret.key=sparkminio
    spark.hadoop.fs.s3a.endpoint=http://192.168.1.5:9000
    spark.hadoop.fs.s3a.path.style.access=true
    spark.hadoop.fs.s3a.connection.ssl.enabled=false

    # spark history server configs
    spark.history.fs.logDirectory=s3a://spark-on-kube/event-logs/

    # spark submit configs
    spark.eventLog.enabled=true
    spark.eventLog.dir=s3a://spark-on-kube/event-logs/